// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALoX1HWJkLf-bHKrfBay4LDtfFIebd_Oo',
    appId: '1:445406266474:web:f0f05785d05272d7fbb613',
    messagingSenderId: '445406266474',
    projectId: 'bookly-app-26',
    authDomain: 'bookly-app-26.firebaseapp.com',
    storageBucket: 'bookly-app-26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuPul1HvOTS5t1euhSTQc89--KpG01T8',
    appId: '1:445406266474:android:0bbd3178d5923512fbb613',
    messagingSenderId: '445406266474',
    projectId: 'bookly-app-26',
    storageBucket: 'bookly-app-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCT2krzw2XLwOLGG-d3TGn6IvLXQrUAMY',
    appId: '1:445406266474:ios:fe2cf5da5998a515fbb613',
    messagingSenderId: '445406266474',
    projectId: 'bookly-app-26',
    storageBucket: 'bookly-app-26.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCT2krzw2XLwOLGG-d3TGn6IvLXQrUAMY',
    appId: '1:445406266474:ios:fe2cf5da5998a515fbb613',
    messagingSenderId: '445406266474',
    projectId: 'bookly-app-26',
    storageBucket: 'bookly-app-26.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALoX1HWJkLf-bHKrfBay4LDtfFIebd_Oo',
    appId: '1:445406266474:web:834acd2e66cc7a1ffbb613',
    messagingSenderId: '445406266474',
    projectId: 'bookly-app-26',
    authDomain: 'bookly-app-26.firebaseapp.com',
    storageBucket: 'bookly-app-26.firebasestorage.app',
  );
}
